### ISSUE TITLE
Show Validation Error message on hover

### ISSUE THREAD

**Issue by AshutoshJha15** [muhimasri/b-editable-table#31]
Hi, Is there any way to show an error message on hovering over a particular row?

**Comment by muhimasri** [comment]
Hi there! There is no out of the box solution but since b-editable-table inherits all features from BootstrapVue, you can use @row-hovered event - https://bootstrap-vue.org/docs/components/table#component-reference

You can capture the id of the hovered row and based on that display a tooltip of the error. Please let me know if that works.

**Comment by AshutoshJha15** [comment]
Thanks
