### ISSUE TITLE
Append Row at the end (Add, Update and Remove Rows)

### ISSUE THREAD

**Issue by yoursantu** [muhimasri/b-editable-table#37]
Hi,
I am using [Add, Update and Remove Rows](https://b-editable-table.muhimasri.com/guide/add-update-and-remove-rows.html) example for one of my project.

In this example Add Action will be adding the new row at the beginning of the table. But i wanted to be append new row at the end of the row.
Is there any way to solve this!?

Thank you.

**Comment by muhimasri** [comment]
Hello,

Currently, it only adds the row at the beginning of the table. The reason was, if there was paging, the new row would not get lost at the very end of the table. That being said, I will add an option to enable adding a row at the end of the table in the next release.

I'm aiming to do an update next week so stay tuned!

**Comment by muhimasri** [comment]
Please install latest v1.0.0. You can now pass `addPosition: "end"` to the `rowUpdate` object  to add rows at the end of the table.

https://b-editable-table.muhimasri.com/guide/add-update-and-remove-rows.html

**Comment by yoursantu** [comment]
Hi,
Thank you, Thanks a lot for the enhancement.

**Comment by muhimasri** [comment]
You're welcome!
